### ISSUE TITLE
Cannot Handle Cusomt Scalars

### ISSUE THREAD

**Issue by s-r-jones** [tgriesser/cypress-graphql-mock#17]
I am importing my schema as one big json object and seeing this error when I try to run the command.

`GraphQL error: No mock defined for type "DateTime"` 

To reproduce, add the custom DateTime scalar as a type to one of your properties.

**Comment by dmtrKovalenko** [comment]
It is possible with 
```
DateTime(obj, args, context, field) {
    if (obj[field.fieldName]) return obj[field.fieldName]
    return new Date('2019-01-01')
  },
```

**Comment by s-r-jones** [comment]
Thanks for your help. Where would I put this code?

**Comment by sean6bucks** [comment]
For anyone hitting finding this issue and finding it a bit confusing on where to add the scalar type resolver, it can be defined in the `mockGraphql()` config under `mocks`

```js
cy.mockGraphql({
    ...
    mocks: {
        DateTime: () => new Date()
    }
})
```
